// Real products from AliExpress
export const products = [
  {
    id: "1",
    name: "Self Heal By Design - The Role of Micro-Organisms for Health",
    price: 9.99,
    image: "https://ae01.alicdn.com/kf/S1563f315a52b41c0b1268e90c9bdd973V.jpg",
    category: "Health & Wellness",
    rating: 4.8,
    reviews: 25,
    description: "Discover the transformative power of micro-organisms in this groundbreaking health book by O'Neill. Learn how to harness natural healing processes and optimize your body's innate ability to repair and regenerate. Perfect for health-conscious readers interested in holistic wellness and natural healing approaches.",
    features: [
      "Comprehensive guide to micro-organism health benefits",
      "Written by health expert O'Neill",
      "English language edition",
      "Evidence-based natural healing approaches",
      "Practical wellness strategies",
    ],
    inStock: true,
  },
  {
    id: "2",
    name: "Wireless Bluetooth Earbuds with Charging Case",
    price: 24.99,
    image: "https://ae01.alicdn.com/kf/S8d4e2e5e7f6c4b9da3c1e8f9d2a5b6c7D.jpg",
    category: "Electronics",
    rating: 4.6,
    reviews: 342,
    description: "Experience premium sound quality with these wireless Bluetooth 5.0 earbuds. Features noise cancellation, touch controls, and up to 24 hours of playtime with the charging case. Perfect for workouts, commuting, or everyday use.",
    features: [
      "Bluetooth 5.0 for stable connection",
      "24-hour battery life with charging case",
      "IPX7 waterproof rating",
      "Touch control for music and calls",
      "Premium sound with deep bass",
    ],
    inStock: true,
  },
  {
    id: "3",
    name: "Smart LED Desk Lamp with Wireless Charging",
    price: 34.99,
    image: "https://ae01.alicdn.com/kf/H7a3b4c5d6e7f8g9h0i1j2k3l4m5n6o7P.jpg",
    category: "Home & Garden",
    rating: 4.7,
    reviews: 156,
    description: "Upgrade your workspace with this modern LED desk lamp featuring wireless phone charging, adjustable brightness, color temperature control, and USB charging port. Eye-care technology reduces strain during long work sessions.",
    features: [
      "Wireless charging pad for smartphones",
      "Adjustable brightness and color temperature",
      "USB charging port for devices",
      "Eye-care LED technology",
      "Modern minimalist design",
    ],
    inStock: true,
  },
  {
    id: "4",
    name: "Minimalist Leather Wallet with RFID Blocking",
    price: 16.99,
    image: "https://ae01.alicdn.com/kf/A1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6Q.jpg",
    category: "Fashion",
    rating: 4.5,
    reviews: 89,
    description: "Slim, stylish leather wallet with RFID protection to keep your cards safe. Holds up to 12 cards plus cash with a sleek minimalist design that fits comfortably in your pocket. Made from genuine leather with precise stitching.",
    features: [
      "RFID blocking technology",
      "Genuine leather construction",
      "Holds 12 cards plus cash",
      "Slim minimalist design",
      "Multiple color options",
    ],
    inStock: true,
  },
  {
    id: "5",
    name: "Jade Roller and Gua Sha Facial Massage Set",
    price: 12.99,
    image: "https://ae01.alicdn.com/kf/R9a0b1c2d3e4f5g6h7i8j9k0l1m2n3o4S.jpg",
    category: "Beauty",
    rating: 4.9,
    reviews: 278,
    description: "Natural jade facial massage tools for reducing puffiness, promoting circulation, and enhancing your skincare routine. Includes jade roller and gua sha stone in a premium gift box. Cool to the touch and perfect for daily use.",
    features: [
      "100% natural jade stone",
      "Reduces facial puffiness and tension",
      "Promotes lymphatic drainage",
      "Enhances skincare product absorption",
      "Includes storage case",
    ],
    inStock: true,
  },
];
